### ISSUE TITLE
Config Updates

### ISSUE THREAD

**Issue by seanrcollings** [seanrcollings/venture#15]
Currently, Venture provides to major features:
- Browse mode
- Quicklaunch Mode

Both of these mode's configuration is just thrown into the structure, without much concern for overall structure. Much of the top-level configurations only apply to Browse mode and not Quicklaunch, and I don't think that this structure makes this all too clear.
## Example:
```yaml
directories:
- base: /home/sean/sourcecode
  subs:
  - rust
  - crystal
  - ComputerScience/*
  - scripts
  - atomicjolt
exec: "code -r {path} && swaymsg [class=Code] focus"
include_parent_folder: false
quicklaunch:
  ARC:
    icon: "\uF625"
    path: /home/sean/sourcecode/arc
    tags:
    - "\uF81F python"
    - project
rofi:
  theme: /home/sean/.config/rofi/venture.rasi
show_files: true
show_hidden: false
show_icons: true
ui_provider: rofi
use_cache: false

```

## New Configuration Layout
Have a few top-level configuration settings, then nest each mode's configurations under their name. 
```yaml
ui_provider: rofi
rofi:
  theme: /home/sean/.config/rofi/venture.rasi
exec: "code -r {path}" # Exec could be present in all of them, and would fallback to the global if it wasn't provided lower
browse:
  exec: "code -r {path}"
  use_cache: false
  show_files: true
  show_hidden: false
  show_icons: true
  include_parent_folder: false
  directories:
    - base: /home/sean/sourcecode
    subs:
     - rust
     - crystal
      - ComputerScience/*
      - scripts
      - atomicjolt
    # etc...
quicklaunch:
  exec: vim {path}
  items: 
   ARC:
      icon: "\uF625"
      path: /home/sean/sourcecode/arc
      tags:
      - "\uF81F python"
      - project
    Mugenmonkey:
      icon: "\uF737"
      path: ~/mugenmonkey-rails
      tags:
      - "\uE7BA react"
      - "\uE23E ruby"
      - "\uFBE4 typescript"
    Qualtrics:
      icon: "\uFAB4"
      path: ~/sourcecode/atomicjolt/qualtrics/
      tags:
      - "\uE7BA react"
      - work
      - "\uE23E ruby"
    Sway:
      icon: "\uF2D2"
      path: ~/.config/sway/config
      tags:
      - "\uE615 config"
    Venture:
      icon: "\uE771"
      path: ~/sourcecode/venture
      tags:
      - "\uF81F python"
      - rofi
     # etc...
```
